environment:
  nodejs_version: "7"
  APPVEYOR_CACHE_SKIP_RESTORE: "true"
cache:
  - C:\Users\appveyor\AppData\Local\Yarn -> appveyor.yml
  - node_modules -> package.json
  - yarn

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set PATH=%LOCALAPPDATA%\Yarn\config\global\node_modules\.bin;%PATH%
  - yarn global add yarn
  - yarn
  - git submodule sync
  - git submodule update --init --recursive --remote
test_script:
  - ./node_modules/.bin/jest -i

build: off
